#You may need to download the following packages
install.packages("pracma")
install.packages("gbm")
install.packages("ROCR")
install.packages("caret")
install.packages("doParallel")
install.packages("parallel")
install.packages("glmnet")
install.packages("DMwR")
install.packages("randomForest")
install.packages("foreign")
install.packages("e1071")
install.packages("Matrix")
install.packages("SparseM")
install.packages("PRROC")
install.packages("tree")
install.packages("rpart")
install.packages("partykit")
install.packages("MLmetrics")
install.packages("caTools")
install.packages("haven")
install.packages("ggthemes")
install.packages("tidyverse")
install.packages("backports")


install.packages(c("zoo","xts","quantmod","abind")
u <- "https://cran.r-project.org/src/contrib/Archive/DMwR/DMwR_0.4.1.tar.gz"
install.packages(u)
